replicaCount: 1
namespace: illedevelop
image:
  repository: cdelambert/odoo-auguria
  tag: 2f0f658
  pullPolicy: Always
  containerPort: 8069

imagePullSecrets:
  - name: registry-secret
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-connect-timeout	: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  hosts:
    - host:  ille-et-developpement.auguria.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: odoo-erp-tls
      hosts: 
        -  ille-et-developpement.auguria.com
resources:
  {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: DB_HOST
    value: latdior.pgo.svc.cluster.local
  #- name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        #key: db_password
        name: odoo-si-secret
  - name: DB_PORT_5432_TCP_PORT
    value: "5432"
  - name:  DB_ENV_POSTGRES_USER
    value: odoo
persistence:
  enabled: true
  storageClass: csi-cinder-high-speed
  accessMode: ReadWriteOnce
  size: 1Gi
  mounthPath: /home/odoo_filestore
  hostPath: /
  existingClaim: erp-odoo
